export const roleTree = [
 {
  "title": "平台管理",
  "open": false,
  "pgco": "menuList_root",
  "gco": "platformManage",
  "checked": null,
  "href": "/platformManage",
  "sort": "10",
  "id": null,
  "icon": null,
  "target": null,
  "shortname": null,
  "menuflag": "file",
  "belongToApp": null,
  "menuType": null,
  "aliasname": null,
  "eddt": null,
  "children": [
   {
    "title": "商户管理",
    "open": false,
    "pgco": "platformManage",
    "gco": "platformManage_merchantManage",
    "checked": null,
    "href": "/platformManage/merchantManage",
    "sort": "10",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "platformManage_merchantManage",
      "gco": "platformManage_merchantManage_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "查看",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_view",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "编辑",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_edit",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(单条)",
        "open": false,
        "pgco": "platformManage_merchantManage_list",
        "gco": "platformManage_merchantManage_delete",
        "checked": false,
        "href": null,
        "sort": "70",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "platformManage_merchantManage",
      "gco": "platformManage_merchantManage_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "提交",
        "open": false,
        "pgco": "platformManage_merchantManage_form",
        "gco": "platformManage_merchantManage_submit",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   }
  ]
 },
 {
  "title": "会员管理",
  "open": false,
  "pgco": "menuList_root",
  "gco": "memberManage",
  "checked": null,
  "href": "/memberManage",
  "sort": "20",
  "id": null,
  "icon": null,
  "target": null,
  "shortname": null,
  "menuflag": "file",
  "belongToApp": null,
  "menuType": null,
  "aliasname": null,
  "eddt": null,
  "children": [
   {
    "title": "充值记录",
    "open": false,
    "pgco": "memberManage",
    "gco": "memberManage_rechargeRecord",
    "checked": null,
    "href": "/memberManage/rechargeRecord",
    "sort": "10",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "memberManage_rechargeRecord",
      "gco": "memberManage_rechargeRecord_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "memberManage_rechargeRecord_list",
        "gco": "memberManage_rechargeRecord_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "memberManage_rechargeRecord_list",
        "gco": "memberManage_rechargeRecord_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "memberManage_rechargeRecord",
      "gco": "memberManage_rechargeRecord_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": []
     }
    ]
   },
   {
    "title": "红包记录",
    "open": false,
    "pgco": "memberManage",
    "gco": "memberManage_redPacketRecord",
    "checked": null,
    "href": "/memberManage/redPacketRecord",
    "sort": "20",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "memberManage_redPacketRecord",
      "gco": "memberManage_redPacketRecord_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "memberManage_redPacketRecord_list",
        "gco": "memberManage_redPacketRecord_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "memberManage_redPacketRecord_list",
        "gco": "memberManage_redPacketRecord_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "memberManage_redPacketRecord",
      "gco": "memberManage_redPacketRecord_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": []
     }
    ]
   },
   {
    "title": "会员等级",
    "open": false,
    "pgco": "memberManage",
    "gco": "memberManage_memberLevel",
    "checked": null,
    "href": "/memberManage/memberLevel",
    "sort": "30",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "memberManage_memberLevel",
      "gco": "memberManage_memberLevel_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "编辑",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_edit",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(单条)",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_delete",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "添加人员",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_add_user",
        "checked": false,
        "href": null,
        "sort": "70",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "查看人员",
        "open": false,
        "pgco": "memberManage_memberLevel_list",
        "gco": "memberManage_memberLevel_view_user",
        "checked": false,
        "href": null,
        "sort": "80",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "memberManage_memberLevel",
      "gco": "memberManage_memberLevel_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "提交",
        "open": false,
        "pgco": "memberManage_memberLevel_form",
        "gco": "memberManage_memberLevel_submit",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "弹窗取消",
        "open": false,
        "pgco": "memberManage_memberLevel_form",
        "gco": "memberManage_memberLevel_dialog_cancel",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "弹窗保存",
        "open": false,
        "pgco": "memberManage_memberLevel_form",
        "gco": "memberManage_memberLevel_dialog_save",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "弹窗删除",
        "open": false,
        "pgco": "memberManage_memberLevel_form",
        "gco": "memberManage_memberLevel_dialog_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   }
  ]
 },
 {
  "title": "打印",
  "open": false,
  "pgco": "menuList_root",
  "gco": "print",
  "checked": null,
  "href": "/print",
  "sort": "30",
  "id": null,
  "icon": null,
  "target": null,
  "shortname": null,
  "menuflag": "file",
  "belongToApp": null,
  "menuType": null,
  "aliasname": null,
  "eddt": null,
  "children": [
   {
    "title": "单张",
    "open": false,
    "pgco": "print",
    "gco": "print_single",
    "checked": null,
    "href": "/print/single",
    "sort": "10",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "print_single",
      "gco": "print_single_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "print_single_list",
        "gco": "print_single_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "print_single_list",
        "gco": "print_single_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "print_single_list",
        "gco": "print_single_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "print_single_list",
        "gco": "print_single_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "查看",
        "open": false,
        "pgco": "print_single_list",
        "gco": "print_single_view",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "支付剩余",
        "open": false,
        "pgco": "print_single_list",
        "gco": "print_single_pay_remaining",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "print_single",
      "gco": "print_single_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "下载",
        "open": false,
        "pgco": "print_single_form",
        "gco": "print_single_download",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "立即购买",
        "open": false,
        "pgco": "print_single_form",
        "gco": "print_single_buy_now",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "取消支付",
        "open": false,
        "pgco": "print_single_form",
        "gco": "print_single_cancel_pay",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   }
  ]
 },
 {
  "title": "订单管理",
  "open": false,
  "pgco": "menuList_root",
  "gco": "order",
  "checked": null,
  "href": "/order",
  "sort": "40",
  "id": null,
  "icon": null,
  "target": null,
  "shortname": null,
  "menuflag": "file",
  "belongToApp": null,
  "menuType": null,
  "aliasname": null,
  "eddt": null,
  "children": [
   {
    "title": "订单列表",
    "open": false,
    "pgco": "order",
    "gco": "order_orderList",
    "checked": null,
    "href": "/order/orderList",
    "sort": "10",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "order_orderList",
      "gco": "order_orderList_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "查看",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_view",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "编辑",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_edit",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(单条)",
        "open": false,
        "pgco": "order_orderList_list",
        "gco": "order_orderList_delete",
        "checked": false,
        "href": null,
        "sort": "70",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "order_orderList",
      "gco": "order_orderList_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "提交",
        "open": false,
        "pgco": "order_orderList_form",
        "gco": "order_orderList_submit",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   }
  ]
 },
 {
  "title": "系统管理",
  "open": false,
  "pgco": "menuList_root",
  "gco": "home",
  "checked": null,
  "href": "/home",
  "sort": "50",
  "id": null,
  "icon": null,
  "target": null,
  "shortname": null,
  "menuflag": "file",
  "belongToApp": null,
  "menuType": null,
  "aliasname": null,
  "eddt": null,
  "children": [
   {
    "title": "菜单管理",
    "open": false,
    "pgco": "home",
    "gco": "home_menuManage",
    "checked": null,
    "href": "/menuManage",
    "sort": "10",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "home_menuManage",
      "gco": "home_menuManage_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "查看",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_view",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "编辑",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_edit",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(单条)",
        "open": false,
        "pgco": "home_menuManage_list",
        "gco": "home_menuManage_delete",
        "checked": false,
        "href": null,
        "sort": "70",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "home_menuManage",
      "gco": "home_menuManage_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "提交",
        "open": false,
        "pgco": "home_menuManage_form",
        "gco": "home_menuManage_submit",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   },
   {
    "title": "角色管理",
    "open": false,
    "pgco": "home",
    "gco": "home_roleManage",
    "checked": null,
    "href": "/roleManage",
    "sort": "20",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "home_roleManage",
      "gco": "home_roleManage_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "编辑",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_edit",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(单条)",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_delete",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "添加用户",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_add_user",
        "checked": false,
        "href": null,
        "sort": "70",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "查看用户",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_view_user",
        "checked": false,
        "href": null,
        "sort": "80",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "角色权限",
        "open": false,
        "pgco": "home_roleManage_list",
        "gco": "home_roleManage_role_perm",
        "checked": false,
        "href": null,
        "sort": "90",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "home_roleManage",
      "gco": "home_roleManage_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "提交",
        "open": false,
        "pgco": "home_roleManage_form",
        "gco": "home_roleManage_submit",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "用户弹窗取消",
        "open": false,
        "pgco": "home_roleManage_form",
        "gco": "home_roleManage_user_dialog_cancel",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "用户弹窗保存",
        "open": false,
        "pgco": "home_roleManage_form",
        "gco": "home_roleManage_user_dialog_save",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "用户弹窗删除",
        "open": false,
        "pgco": "home_roleManage_form",
        "gco": "home_roleManage_user_dialog_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "权限弹窗取消",
        "open": false,
        "pgco": "home_roleManage_form",
        "gco": "home_roleManage_perm_dialog_cancel",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "权限弹窗保存",
        "open": false,
        "pgco": "home_roleManage_form",
        "gco": "home_roleManage_perm_dialog_save",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   },
   {
    "title": "用户管理",
    "open": false,
    "pgco": "home",
    "gco": "home_userManage",
    "checked": null,
    "href": "/userManage",
    "sort": "30",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "file",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "列表",
      "open": false,
      "pgco": "home_userManage",
      "gco": "home_userManage_list",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "查询",
        "open": false,
        "pgco": "home_userManage_list",
        "gco": "home_userManage_query",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "重置",
        "open": false,
        "pgco": "home_userManage_list",
        "gco": "home_userManage_reset",
        "checked": false,
        "href": null,
        "sort": "20",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "新增",
        "open": false,
        "pgco": "home_userManage_list",
        "gco": "home_userManage_add",
        "checked": false,
        "href": null,
        "sort": "30",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(批量)",
        "open": false,
        "pgco": "home_userManage_list",
        "gco": "home_userManage_batch_delete",
        "checked": false,
        "href": null,
        "sort": "40",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "编辑",
        "open": false,
        "pgco": "home_userManage_list",
        "gco": "home_userManage_edit",
        "checked": false,
        "href": null,
        "sort": "50",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       },
       {
        "title": "删除(单条)",
        "open": false,
        "pgco": "home_userManage_list",
        "gco": "home_userManage_delete",
        "checked": false,
        "href": null,
        "sort": "60",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     },
     {
      "title": "表单",
      "open": false,
      "pgco": "home_userManage",
      "gco": "home_userManage_form",
      "checked": false,
      "href": null,
      "sort": "20",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": [
       {
        "title": "提交",
        "open": false,
        "pgco": "home_userManage_form",
        "gco": "home_userManage_submit",
        "checked": false,
        "href": null,
        "sort": "10",
        "id": null,
        "icon": null,
        "target": null,
        "shortname": null,
        "menuflag": "button",
        "belongToApp": null,
        "menuType": null,
        "aliasname": null,
        "eddt": null,
        "children": null
       }
      ]
     }
    ]
   }
  ]
 },
 {
  "title": "积分设置",
  "open": false,
  "pgco": "menuList_root",
  "gco": "pointsSetting",
  "checked": null,
  "href": "/pointsSetting",
  "sort": "60",
  "id": null,
  "icon": null,
  "target": null,
  "shortname": null,
  "menuflag": "file",
  "belongToApp": null,
  "menuType": null,
  "aliasname": null,
  "eddt": null,
  "children": [
   {
    "title": "列表",
    "open": false,
    "pgco": "pointsSetting",
    "gco": "pointsSetting_list",
    "checked": false,
    "href": null,
    "sort": "10",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "button",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": []
   },
   {
    "title": "表单",
    "open": false,
    "pgco": "pointsSetting",
    "gco": "pointsSetting_form",
    "checked": false,
    "href": null,
    "sort": "20",
    "id": null,
    "icon": null,
    "target": null,
    "shortname": null,
    "menuflag": "button",
    "belongToApp": null,
    "menuType": null,
    "aliasname": null,
    "eddt": null,
    "children": [
     {
      "title": "保存配置",
      "open": false,
      "pgco": "pointsSetting_form",
      "gco": "pointsSetting_save_settings",
      "checked": false,
      "href": null,
      "sort": "10",
      "id": null,
      "icon": null,
      "target": null,
      "shortname": null,
      "menuflag": "button",
      "belongToApp": null,
      "menuType": null,
      "aliasname": null,
      "eddt": null,
      "children": null
     }
    ]
   }
  ]
 }
]